### ISSUE TITLE
weird IS_ADMIN var

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-report_coursecompletion#12]
the handling of capabiltiies and the IS_ADMIN var needs rewriting to be more "Moodley"

**Comment by ak4t0sh** [comment]
+1 ! 
Moreover it makes code a lot of more complicated to read (and so to maintain).
And (even if limited to index.php) "IS_ADMIN" do not match naming convention (https://docs.moodle.org/dev/Coding_style#Functions_and_Methods, https://docs.moodle.org/dev/Coding_style#Constants).

**Comment by danmarsden** [comment]
@boGitsIT - looking back at this I realise that I haven't explained very well what is the "right" way to do this...

A define is the wrong way to go here, and "isadmin" is the wrong name for what it is doing.
a better solution is to have a simple var called something like "$showallusers = false"
and then at the top of the file where the report/coursecompletion:viewall' capabiltiy is checked - if the user has that capability we set the var to "true"
and then when calling the form you pass that $showallusers var to the form so that it can be checked when deciding whether to display the extra elements - see here for the docs:
https://docs.moodle.org/dev/lib/formslib.php_Form_Definition#Passing_parameters_to_the_Form

thanks!
