### ISSUE TITLE
php end tags!

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-report_coursecompletion#15]
PHP end tags should be removed from the ends of files like settings.php

**Comment by boGitsIT** [comment]
I have not found any PHP end tags in this plugin.
It may be time to close this issue.

**Comment by danmarsden** [comment]
are you looking at the right code? - I see them in almost every file here in the master branch.

**Comment by boGitsIT** [comment]
Ah, sorry. I accidentally fixed this issue before the holiday with phpcbf. (see today's pull request)
