### ISSUE TITLE
should use has_any_capability api

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-report_coursecompletion#16]
This stuff should be rewritten to a has_any_capability check instead.
https://github.com/catalyst/moodle-report_coursecompletion/blob/master/index.php#L44

**Comment by boGitsIT** [comment]
I have not found any PHP end tags in this plugin. 
It may be time to close this issue.

**Comment by danmarsden** [comment]
rewrote it to simplify it down a lot.
