### ISSUE TITLE
pix_url is deprecated

### ISSUE THREAD

**Issue by ak4t0sh** [catalyst/moodle-report_coursecompletion#20]
https://github.com/catalyst/moodle-report_coursecompletion/blob/20d0dee62c1aeded7bc0feaa0ff5359cea56398c/index.php#L299

`$OUTPUT->pix_url()` has been deprecated in Moodle 3.3.
You can replace it using `$OUTPUT->image_url()`
See corresponding change note in [lib/upgrade.txt#L408](https://github.com/moodle/moodle/blob/9f997f9bd7edc6ea0b4371804f9a78b84f866e51/lib/upgrade.txt#L408)

**Comment by danmarsden** [comment]
@boGitsIT - this one too?
