### ISSUE TITLE
avoid unnecessary abstraction

### ISSUE THREAD

**Issue by ak4t0sh** [catalyst/moodle-report_coursecompletion#22]
https://github.com/catalyst/moodle-report_coursecompletion/blob/20d0dee62c1aeded7bc0feaa0ff5359cea56398c/index.php#L350

You should avoid such function which only make code more complicated to read and maintain.

**Comment by ak4t0sh** [comment]
same for your functions used to build DB queries...its handy but make code hard to read.

**Comment by danmarsden** [comment]
@boGitsIT - I commented on this one in the pull request too.
